### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by drwlrsn** [BridgeCityBicycleCoop/workstand#28]
Now that I have moved over to a docker-compose, the README needs to be updated to describe how to get the project running locally.

**Comment by foltra** [comment]
I'm leaving a comment here because it seems to be on topic. 
My local installation of docker engine is  *Docker on Mac* and doesn't have docker-machine.
I followed the instructions on the README and had no problem getting the services up, but had to modify references to `http://192.168.99.100` to point to `http://localhost` in this file: `bikeshop_project/webpack.dev.config.js` .

One shouldn't need to run docker-machine, boot2iso and VirtualBox anymore: 

[Docker for Mac vs Docker Toolbox](https://docs.docker.com/docker-for-mac/docker-toolbox/)

**Comment by fspc** [comment]
While I haven't requested a PR, yet, in my fork there is an aggregated working example: https://github.com/fspc/workstand/commit/53ed002440eb61cc04523923ed2c6be48facf9a4 .  The compose files uses jwilder/nginx-proxy and JrCs/docker-letsencrypt-nginx-proxy-companion, which I recommend for simplicity,  but that can easily be swapped out for something else, and env variables can easily be altered.   I am using this setup for https://workstand.bikelover.org.

All you need to do:

```
docker-compose -f docker-compose.demo.yml build
docker-compose -f docker-compose.demo.yml up -d
```
and you are good to go.
